### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by shamird** [PeterStaev/az_notification_hub#1]
az_notification_hub/AzureNotificationHubPlugin.swift:77: Fatal error: Unexpectedly found nil while unwrapping an Optional value

This happens, when main.dart runs, "await AzureNotificationHub.instance.start();"

**Comment by PeterStaev** [comment]
Hey @shamird , seems you haven't set up the connection strings:
https://github.com/PeterStaev/az_notification_hub/blob/02ce047880e735bd80a996f74132749e1e6e4ca0/ios/Classes/AzureNotificationHubPlugin.swift#L77

Make sure you follow up the setup instructions. Also if you have already done it, a clean build might be needed in order to pick up the settings.

**Comment by shamird** [comment]
Thank you! My mistake was putting both live and test servers in an array under the connection strings. Sorry to get back to you so late.
